version: "3.8"

volumes:
  postgres-data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      # Ensure that the variables in .env match the same variables in devcontainer.json
      - ../.env

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
  worker:
    image: contribsys/faktory
    env_file:
      # Ensure that the variables in .env match the same variables in devcontainer.json
      - ../.env
    ports:
      - "7419:7419"
      - "7420:7420"
